language: ruby
sudo: false
script: "bundle exec rake"

branches:
  only:
    - master

rvm:
  - 2.0.0
  - 2.1.4
  - 2.2.0

gemfile:
  - gemfiles/4.0.0.gemfile
  - gemfiles/4.0.1.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
